apiVersion: apps/v1
kind: Deployment
metadata:
  name: heart-api
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: heart-api
  template:
    metadata:
      labels:
        app: heart-api
    spec:
      containers:
        - name: heart-api
          image: asiftech67/heart-api:latest
          imagePullPolicy: Always

          ports:
            - containerPort: 8000

          # ✅ DO NOT override MODEL_PATH (or set it correctly)
          # env:
          #   - name: MODEL_PATH
          #     value: /app/models/model.pkl

          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 20
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 40
            periodSeconds: 20

          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
